# .github/workflows/ci.yml
name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

       - name: Set SHORT_SHA
         run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
         shell: bash
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: faruq96/todo-backend:${{ env.SHORT_SHA }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          push: true
          tags: faruq96/todo-frontend:${{ env.SHORT_SHA }}